/usr/share/printrun/blupload.py
/usr/share/printrun/bufferedcanvas.py
/usr/share/printrun/calibrateextruder.py
/usr/share/printrun/custombtn.txt
/usr/share/printrun/gviz.py
/usr/share/printrun/P-face.ico
/usr/share/printrun/plater.ico
/usr/share/printrun/plater.py
/usr/share/printrun/printcore.py
/usr/share/printrun/pronsole.ico
/usr/share/printrun/pronsole.py
/usr/share/printrun/stltool.py
/usr/debian/tmp/usr/bin/pronsole

